
SOURCES = $(wildcard *.c)

INCLUDE_DIRS := ../../include

LIBRARY_BASE := common
LIBRARY_STATIC := $(LIBRARY_BASE).a


include ../../Makefile.config
include ../../Makefile.common

all:	$(BUILD_DIR) $(OUTPUT_DIR) $(OUTPUT_DIR)/$(LIBRARY_STATIC)
